In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path

In [2]:
# File to Load
node_path = Path("Datasets/NODE.csv")
accident_path = Path("Datasets/ACCIDENT.csv")

In [3]:
# Read the CSV file
node_data = pd.read_csv(node_path, low_memory=False)
accident_data = pd.read_csv(accident_path, low_memory=False)

In [4]:
# Store it in a Dataframe
node_data_df = pd.DataFrame(node_data)
node_data_df

,ACCIDENT_NO,NODE_ID,NODE_TYPE,VICGRID94_X,VICGRID94_Y,LGA_NAME,LGA_NAME_ALL,REGION_NAME,DEG_URBAN_NAME,Lat,Long,POSTCODE_NO
0,T20060002689,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
1,T20060010827,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
2,T20060017279,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
3,T20060041762,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
4,T20060047478,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,144.951197,3051
...,...,...,...,...,...,...,...,...,...,...,...,...
221792,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.645401,144.991064,3076
221793,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,RURAL_VICTORIA,-37.645401,144.991064,3076
221794,T20090047746,229114,N,2508240.178,2412119.954,BOROONDARA,BOROONDARA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.791877,145.093559,3104
221795,T20090044445,229087,N,2653269.886,2599283.209,INDIGO,INDIGO,NORTH EASTERN REGION,RURAL_VICTORIA,-36.092861,146.702041,3688
221796,T20090046194,229105,N,2592208.478,2362963.486,BAW BAW,BAW BAW,EASTERN REGION,RURAL_VICTORIA,-38.230181,146.053062,3823

In [5]:
# Store it in a Dataframe
accident_data_df = pd.DataFrame(accident_data)
accident_data_df.head()

,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident_Type_Desc,DAY_OF_WEEK,Day_Week_Description,DCA_CODE,DCA_Description,DIRECTORY,...,NO_PERSONS,NO_PERSONS_INJ_2,NO_PERSONS_INJ_3,NO_PERSONS_KILLED,NO_PERSONS_NOT_INJ,POLICE_ATTEND,ROAD_GEOMETRY,Road_Geometry_Desc,SEVERITY,SPEED_ZONE
0,T20060000010,13/01/2006,12:42:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),MEL,...,6,0,1,0,5,1,1,Cross intersection,3,60
1,T20060000018,13/01/2006,19:10:00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),MEL,...,4,0,1,0,3,1,2,T intersection,3,70
2,T20060000022,14/01/2006,12:10:00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,MEL,...,2,1,0,0,1,1,5,Not at intersection,2,100
3,T20060000023,14/01/2006,11:49:00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),MEL,...,2,1,0,0,1,1,2,T intersection,2,80
4,T20060000026,14/01/2006,10:45:00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,MEL,...,3,0,3,0,0,1,5,Not at intersection,3,50

In [6]:
left_join = pd.merge(node_data_df, accident_data_df, on='ACCIDENT_NO', how='left')
left_join

,ACCIDENT_NO,NODE_ID_x,NODE_TYPE,VICGRID94_X,VICGRID94_Y,LGA_NAME,LGA_NAME_ALL,REGION_NAME,DEG_URBAN_NAME,Lat,...,NO_PERSONS,NO_PERSONS_INJ_2,NO_PERSONS_INJ_3,NO_PERSONS_KILLED,NO_PERSONS_NOT_INJ,POLICE_ATTEND,ROAD_GEOMETRY,Road_Geometry_Desc,SEVERITY,SPEED_ZONE
0,T20060002689,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,...,2,0,1,0,1,2,1,Cross intersection,2,60
1,T20060010827,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,...,2,1,0,0,1,1,1,Cross intersection,3,50
2,T20060017279,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,...,2,1,1,0,0,1,1,Cross intersection,2,60
3,T20060041762,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,...,2,0,1,0,1,2,1,Cross intersection,3,50
4,T20060047478,22,I,2495701.925,2411599.135,MELBOURNE,MELBOURNE,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.796596,...,6,1,2,0,3,1,1,Cross intersection,3,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221792,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,MELB_URBAN,-37.645401,...,1,0,1,0,0,1,5,Not at intersection,2,100
221793,T20090046106,229103,N,2499211.462,2428380.388,WHITTLESEA,WHITTLESEA,METROPOLITAN NORTH WEST REGION,RURAL_VICTORIA,-37.645401,...,1,0,1,0,0,1,5,Not at intersection,2,100
221794,T20090047746,229114,N,2508240.178,2412119.954,BOROONDARA,BOROONDARA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,-37.791877,...,2,1,1,0,0,1,2,T intersection,3,60
221795,T20090044445,229087,N,2653269.886,2599283.209,INDIGO,INDIGO,NORTH EASTERN REGION,RURAL_VICTORIA,-36.092861,...,2,2,0,0,0,1,5,Not at intersection,2,110
221796,T20090046194,229105,N,2592208.478,2362963.486,BAW BAW,BAW BAW,EASTERN REGION,RURAL_VICTORIA,-38.230181,...,2,0,1,0,1,1,5,Not at intersection,3,100

In [7]:
# Find columns with missing values
columns_with_missing_values = left_join.isnull().any()

# Display the columns with missing values
columns_with_missing_values

ACCIDENT_NO             False
NODE_ID_x               False
NODE_TYPE               False
VICGRID94_X             False
VICGRID94_Y             False
LGA_NAME                False
LGA_NAME_ALL            False
REGION_NAME             False
DEG_URBAN_NAME          False
Lat                     False
Long                    False
POSTCODE_NO             False
ACCIDENTDATE            False
ACCIDENTTIME            False
ACCIDENT_TYPE           False
Accident_Type_Desc      False
DAY_OF_WEEK             False
Day_Week_Description    False
DCA_CODE                False
DCA_Description         False
DIRECTORY                True
EDITION                  True
PAGE                     True
GRID_REFERENCE_X         True
GRID_REFERENCE_Y         True
LIGHT_CONDITION         False
Light_Condition_Desc    False
NODE_ID_y               False
NO_OF_VEHICLES          False
NO_PERSONS              False
NO_PERSONS_INJ_2        False
NO_PERSONS_INJ_3        False
NO_PERSONS_KILLED       False
NO_PERSONS_NOT_INJ      False
POLICE_ATTEND           False
ROAD_GEOMETRY           False
Road_Geometry_Desc      False
SEVERITY                False
SPEED_ZONE              False
dtype: bool

In [8]:
# Drop columns with missing values
df_dropped = left_join.drop(columns=columns_with_missing_values[columns_with_missing_values].index, inplace=True)
df_dropped

In [9]:
# Storing file in Data folder
merged_data_output_path = Path("Cleaned_Datasets/merged_cleaned.csv")
left_join.to_csv(merged_data_output_path, index=None, header=True)